apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-subdir-helm-chart-value-overrides
  namespace: nfs-subdir
data:
  values.yaml: |-  
    # <upstream values go here>
    nfs:
      server: 10.0.0.6
      path: /nfsdata
      mountOptions:
         - hard
         - nfsvers=4.1
    storageClass:
      defaultClass: true          
