---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: kustomization
metdata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
  interval: 1m0s
  path: ./apps/base/nfs-subdir-external-provisioner
  prune: false
  sourceRef:
    kind: HelmRepository
    name: flux-system
  validation: client
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: nfs-subdir
          namespace: flux-system
        spec:
          chart:
            spec:
              chart: nfs-subdir-external-provisioner
              version: 4.0.8
              sourceRef:
                kind: HelmRepository
                name: nfs-subdir-external-provisioner
                namespace: flux-system       
          interval: 30m
          timeout: 5m
          releaseName: nfs-subdir-external-provisioner
          valuesFrom:
          - kind: ConfigMap
            name: nfs-subdir-helm-chart-value-overrides
            valuesKey: values.yaml # This is the default, but best to be explicit for clarity
