apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-subdir
  namespace: flux-system
spec:
  interval: 15m
  path: ./nfs-subdir
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    #healthChecks:
    #- apiVersion: apps/v1
    #  kind: Deployment
    #  name: nfs-subdir-external-provisioner
    #  namespace: nfs-suibdir
