apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-subdir
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
  interval: 1m0s
  path: ./flux-clusters/npd-cluster
  prune: false
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    #healthChecks:
    #- apiVersion: apps/v1
    #  kind: Deployment
    #  name: nfs-subdir-external-provisioner
    #  namespace: nfs-suibdir
