apiVersion: kustomize.config.k8s.io/v1beta1
kind: kustomization
namespace: flux-system
resources:
- ../base


patchesJson6902:
#nfs-subdir-external-provisioner
- target:
    version: v1beta2
    group: kustomize.toolkit.fluxcd.io
    kind: kustomization
    name: nfs-subdir
    namespace: flux-system
  patch: |-
    - op: replace
      path: /spec/patches/0/patch
      value: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: nfs-subdir
          namespace: flux-system
        spec:
          chart: 
            spec:
              chart: nfs-subdir-external-provisioner
              version: "4.0.18"         
